<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUTSRlrg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUTSRlrg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUTSRlrg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUTSRlrg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUTSRlrg\App_KernelDevDebugContainer([
    'container.build_hash' => 'UTSRlrg',
    'container.build_id' => '26fb2a2a',
    'container.build_time' => 1585311074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUTSRlrg');
