<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSeY39Rx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSeY39Rx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSeY39Rx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSeY39Rx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSeY39Rx\App_KernelDevDebugContainer([
    'container.build_hash' => 'SeY39Rx',
    'container.build_id' => '6e77992d',
    'container.build_time' => 1585228720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSeY39Rx');
