<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxKryZF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxKryZF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxKryZF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxKryZF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxKryZF\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxKryZF',
    'container.build_id' => '617c0ea5',
    'container.build_time' => 1584963612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxKryZF');
